/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyPathRouteImport } from './routes/study-path'
import { Route as StudyAssistantRouteImport } from './routes/study-assistant'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as MindMapRouteImport } from './routes/mind-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangeContextRouteImport } from './routes/change-context'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrioritiesTopicIdRouteImport } from './routes/priorities.$topicId'

const StudyPathRoute = StudyPathRouteImport.update({
  id: '/study-path',
  path: '/study-path',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAssistantRoute = StudyAssistantRouteImport.update({
  id: '/study-assistant',
  path: '/study-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const MindMapRoute = MindMapRouteImport.update({
  id: '/mind-map',
  path: '/mind-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeContextRoute = ChangeContextRouteImport.update({
  id: '/change-context',
  path: '/change-context',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesTopicIdRoute = PrioritiesTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => PrioritiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mind-map': typeof MindMapRoute
  '/priorities': typeof PrioritiesRouteWithChildren
  '/progress': typeof ProgressRoute
  '/quizzes': typeof QuizzesRoute
  '/stats': typeof StatsRoute
  '/study-assistant': typeof StudyAssistantRoute
  '/study-path': typeof StudyPathRoute
  '/priorities/$topicId': typeof PrioritiesTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mind-map': typeof MindMapRoute
  '/priorities': typeof PrioritiesRouteWithChildren
  '/progress': typeof ProgressRoute
  '/quizzes': typeof QuizzesRoute
  '/stats': typeof StatsRoute
  '/study-assistant': typeof StudyAssistantRoute
  '/study-path': typeof StudyPathRoute
  '/priorities/$topicId': typeof PrioritiesTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/mind-map': typeof MindMapRoute
  '/priorities': typeof PrioritiesRouteWithChildren
  '/progress': typeof ProgressRoute
  '/quizzes': typeof QuizzesRoute
  '/stats': typeof StatsRoute
  '/study-assistant': typeof StudyAssistantRoute
  '/study-path': typeof StudyPathRoute
  '/priorities/$topicId': typeof PrioritiesTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/flashcards'
    | '/insights'
    | '/login'
    | '/mind-map'
    | '/priorities'
    | '/progress'
    | '/quizzes'
    | '/stats'
    | '/study-assistant'
    | '/study-path'
    | '/priorities/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/flashcards'
    | '/insights'
    | '/login'
    | '/mind-map'
    | '/priorities'
    | '/progress'
    | '/quizzes'
    | '/stats'
    | '/study-assistant'
    | '/study-path'
    | '/priorities/$topicId'
  id:
    | '__root__'
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/flashcards'
    | '/insights'
    | '/login'
    | '/mind-map'
    | '/priorities'
    | '/progress'
    | '/quizzes'
    | '/stats'
    | '/study-assistant'
    | '/study-path'
    | '/priorities/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeContextRoute: typeof ChangeContextRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MindMapRoute: typeof MindMapRoute
  PrioritiesRoute: typeof PrioritiesRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  QuizzesRoute: typeof QuizzesRoute
  StatsRoute: typeof StatsRoute
  StudyAssistantRoute: typeof StudyAssistantRoute
  StudyPathRoute: typeof StudyPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-path': {
      id: '/study-path'
      path: '/study-path'
      fullPath: '/study-path'
      preLoaderRoute: typeof StudyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-assistant': {
      id: '/study-assistant'
      path: '/study-assistant'
      fullPath: '/study-assistant'
      preLoaderRoute: typeof StudyAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind-map': {
      id: '/mind-map'
      path: '/mind-map'
      fullPath: '/mind-map'
      preLoaderRoute: typeof MindMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-context': {
      id: '/change-context'
      path: '/change-context'
      fullPath: '/change-context'
      preLoaderRoute: typeof ChangeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities/$topicId': {
      id: '/priorities/$topicId'
      path: '/$topicId'
      fullPath: '/priorities/$topicId'
      preLoaderRoute: typeof PrioritiesTopicIdRouteImport
      parentRoute: typeof PrioritiesRoute
    }
  }
}

interface PrioritiesRouteChildren {
  PrioritiesTopicIdRoute: typeof PrioritiesTopicIdRoute
}

const PrioritiesRouteChildren: PrioritiesRouteChildren = {
  PrioritiesTopicIdRoute: PrioritiesTopicIdRoute,
}

const PrioritiesRouteWithChildren = PrioritiesRoute._addFileChildren(
  PrioritiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeContextRoute: ChangeContextRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MindMapRoute: MindMapRoute,
  PrioritiesRoute: PrioritiesRouteWithChildren,
  ProgressRoute: ProgressRoute,
  QuizzesRoute: QuizzesRoute,
  StatsRoute: StatsRoute,
  StudyAssistantRoute: StudyAssistantRoute,
  StudyPathRoute: StudyPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
