/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyPathRouteImport } from './routes/study-path'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangeContextRouteImport } from './routes/change-context'
import { Route as IndexRouteImport } from './routes/index'

const StudyPathRoute = StudyPathRouteImport.update({
  id: '/study-path',
  path: '/study-path',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeContextRoute = ChangeContextRouteImport.update({
  id: '/change-context',
  path: '/change-context',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/study-path': typeof StudyPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/study-path': typeof StudyPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-context': typeof ChangeContextRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/study-path': typeof StudyPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/login'
    | '/priorities'
    | '/study-path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/login'
    | '/priorities'
    | '/study-path'
  id:
    | '__root__'
    | '/'
    | '/change-context'
    | '/dashboard'
    | '/login'
    | '/priorities'
    | '/study-path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeContextRoute: typeof ChangeContextRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrioritiesRoute: typeof PrioritiesRoute
  StudyPathRoute: typeof StudyPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-path': {
      id: '/study-path'
      path: '/study-path'
      fullPath: '/study-path'
      preLoaderRoute: typeof StudyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-context': {
      id: '/change-context'
      path: '/change-context'
      fullPath: '/change-context'
      preLoaderRoute: typeof ChangeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeContextRoute: ChangeContextRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrioritiesRoute: PrioritiesRoute,
  StudyPathRoute: StudyPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
